import subprocess
import pandas as pd
import os
import sys

# --- CONFIGURATION ---
CSV_PATH = os.path.join("output", "per_ticker_summary_next_open.csv")

def run_stress_engine(comm):
    # This runs the backtester which generates the CSV
    cmd = [
        "python", "Bayes_opt_adapt_RSI.py",
        "--files", "19",
        "--fill", "next_open",
        "--commission_rate_per_side", str(comm),
        "--atrPeriod-fixed", "10",
        "--slMultiplier-fixed", "2.16643442",
        "--tpMultiplier-fixed", "4.90105666",
        "--basePeriod-fixed", "14",
        "--minPeriod-fixed", "4",
        "--maxPeriod-fixed", "14",
        "--fastPeriod-fixed", "2",
        "--slowPeriod-fixed", "15",
        "--smooth_len-fixed", "2",
        "--time-stop", "12",
        "--threshold-mode", "fixed",
        "--threshold-fixed", "0.04",
        "--vol-floor-mult-fixed", "0.55",
        "--min-tp2sl", "0.1",
        "--min-trades", "1"
    ]
    subprocess.run(cmd, capture_output=True, text=True)
    
    # Read the CSV generated by the backtester
    if os.path.exists(CSV_PATH):
        return pd.read_csv(CSV_PATH)
    else:
        print(f"❌ Error: {CSV_PATH} not found.")
        sys.exit(1)

print("🚀 Running Baseline...")
df_base = run_stress_engine(0.0006)

print("🚀 Running Stressed...")
df_stress = run_stress_engine(0.0015)

# Calculate Stress metrics manually on the dataframe
print("\n" + "="*60)
print(f"{'TICKER-LEVEL SURVIVAL REPORT':^60}")
print("="*60)
print(f"{'Ticker':<10} | {'Base PF':<10} | {'Stress PF':<10} | {'Status'}")
print("-" * 60)

for idx, row in df_stress.iterrows():
    ticker = row['ticker']
    s_pf = row['profit_factor']
    # Match with baseline
    b_pf = df_base[df_base['ticker'] == ticker]['profit_factor'].values[0]
    
    status = "✅ PASS" if s_pf > 1.0 else "❌ FAIL"
    print(f"{ticker:<10} | {b_pf:<10.2f} | {s_pf:<10.2f} | {status}")

survival_count = len(df_stress[df_stress['profit_factor'] > 1.0])
print("="*60)
print(f"Survival Rate: {survival_count}/19 ({survival_count/19*100:.1f}%)")